version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.gradle:/home/gradle/.gradle
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://34.47.75.9:3306/studylink
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=studylink123!